### ISSUE TITLE
Cannot add site to warden server

### ISSUE THREAD

**Issue by tingan** [teamdeeson/warden#137]
Exception: Unable to communicate with Warden in WardenAPI->request() (line 205 of sites/all/modules/warden/warden_api.inc)

How to match the drupal 7 site $conf['warden_token'] to the warden server?

**Comment by mikeddeeson** [comment]
Hi @tingan ,

This error would indicate that the request to your Warden server failed for some reason. The details of the error will be in the watchdog/ syslog within your Drupal site, so it would be worth checking this. 

When you install the Warden Drupal module, it will generate a token if one hasn't been set within the settings file. 
So if you want to make sure that this token always remains the same, you can either set the token manually in the settings file _before_ registering the site with Warden, or you can set the token in the settings file with the value of the token that is generated when the Drupal module is installed.

I hope that this helps?

Thanks
Mike

**Comment by tingan** [comment]
Hi,
I set up warden server in mamp pro with php 7.2.8 with https. drupal 7 test site with acquia dev desktop with php 5.6.32 with https also. the error is  as follows:

http://d7test.dd:8083/admin/config/system/warden?render=overlay
https://warden.lc:8890/public-key : 0 : Error opening socket ssl://warden.lc:8890

**Comment by mikeddeeson** [comment]
Hi,

Thanks for the information, I think that this is due to your local Wardens SSL cert probably being a self signed certificate which is meaning that the request is failing as it knows it isn't secure.

You should make sure that when running Warden live that this is running on a valid SSL certificate. However, as you are working locally, you can add the following settings into your sites settings file for Warden to allow an insecure connect. 

```
$conf['warden_context_options'] = array(
  'ssl' => array(
    'verify_host' => FALSE,
    'verify_peer' => FALSE,
    'verify_peer_name' => FALSE,
    'allow_self_signed' => TRUE,
  ),
);
```

Please make sure that these settings are **only** used for local development 😄

**Comment by tingan** [comment]
Hi,
it works now, my warden server can see the drupal site which has warden module enabled. but no data show up in warden server. what command or cron job i need to run to be able to see the data? thx.

**Comment by tingan** [comment]
WD warden: https://warden.lc:8890/site-update : 400 : Bad Request                                     [error]
Unable to communicate with Warden

**Comment by mikeddeeson** [comment]
OK, so it looks like the Warden server is generating an error and will be due to several reasons:

- a mismatch in timestamp (the requests timestamp is checked to make sure that is isn't older than 20ms)
- The sites URL isn't the same as the one registered in Warden (http or https will matter on the site URL)
- The sites token doesn't match

What ever the reason if you have a look in the Warden logs it will be listed in there

**Comment by mikeddeeson** [comment]
Hi @tingan, did you manage to see what was causing the Warden server to generate the error, was it due to a mismatch of timestamps on the servers?

**Comment by mikeddeeson** [comment]
Hi @tingan I am going to close this now as I presume that you have managed to sort this out.

**Comment by carolinechap** [comment]
Hello @mikeddeeson, i have the same trouble as mentionned previously. I actually checked the 3 points you mentionned.

- My warden is on the same server as my website so we cant have any mismatch in timestamp.
- The site url is the same as the one registered.
- The token is the same as well.

I can not find any solution why my warden server generate this error... 
Thanks !!
