### ISSUE TITLE
Warden server dashboard

### ISSUE THREAD

**Issue by DaisyMaeHarris** [teamdeeson/warden#141]
I've install Warden server on Linux Ubuntu. I got the 'Warden installation complete.' success message. Where do I find the dashboard?

I've tried using Docksal to spin up a version of the website - I can browse the server and see the /docroot/index.php file.

Where is the dashboard located? Is it browsable or have I misunderstood?

**Comment by mikeddeeson** [comment]
Hi @DaisyMaeHarris 

Thanks for looking at Warden.

The Warden server is a Symfony application so it runs on webserver configured to run run a Symfony application. The server will therefore need to be configured with whatever domain you have pointed to this server so that the site can be loaded.

Have you configured your server to run the Symfony application on a domain either locally or externally?

Thanks
Mike

**Comment by DaisyMaeHarris** [comment]
Thank you for the swift response. The server is configured to run Symfony applications. It is configured to be able to host multiple sites using name-based vhosts. I have used Docksal and set the environment VIRTUAL_HOST="warden.myurl.com" - I can browse to the URL http://warden.myurl.com in my broswer and see the page called on ~/websitefolder/warden/docroot/index.php.

Is the Warden dashboard be browsable at that URL or have I misunderstood your question?

Perhaps I ought to be reaching the dashboard via my Drupal installations?

I have installed the Warden Drupal module on one of my D7 sites and added the line '$conf[warden_server_host_path] = 'http://';' to my settings.php file, if I go to http://mywebsite.com/admin/config/system/warden and click on 'http://warden.myurl.com' I get:

Notice: Use of undefined constant warden_server_host_path - assumed 'warden_server_host_path' in include_once() (line 639 of /var/www/docroot/sites/default/settings.php).
Exception: Unable to communicate with Warden in WardenAPI->request() (line 205 of /var/www/docroot/sites/all/modules/warden/warden_api.inc).

Apologies if I am asking incorrect questions, or not providing the correct information required. I am such a dev ops newbie.

**Comment by mikeddeeson** [comment]
OK, no problems - as long as you have your Warden server configured correctly, then you should get a login page when you visit http://warden.myurl.com. As part of the setup you will have set your username and password to access the server. Warden only has one login account at the moment so the user name and password are set as part of the installation process.
Once logged in you will see the dashboard of sites that have been registered with your Warden server.

From your server host name, it seems that you aren't running your Warden server securely. We advise that you run Warden under SSL - have you got an SSL certificate for your warden domain?
If you are just running it under HTTP for the moment, did you configure it to not run securely under HTTPS as part of the server installation process?

With regards to the the Drupal module configuration, based upon what you have provided, it looks like it should be `$conf['warden_server_host_path']` - with the variable name wrapped in quotes otherwise PHP is reading this as a const 😄

**Comment by DaisyMaeHarris** [comment]
Thanks again, you are correct - we aim to move to SSL.

As part of the setup I did set my username, password, and HTTP (not-secure).

Thank you for your help with $conf['warden_server_host_path'], I now get this error:

Exception: Unable to communicate with Warden in WardenAPI->request() (line 205 of /var/www/docroot/sites/all/modules/warden/warden_api.inc).

I think you are right - I may not have installed Warden correctly. Inside the Warden folder is a folder called docroot, which contains one file called index.php. This is what I see when I navigate to my URL, I see no dashboard. Perhaps I should try deleting the folder and reinstalling. Should there be files in the 'docroot' folder in Warden?

**Comment by mikeddeeson** [comment]
Did you download the zip file of the latest release or have you forked it and checked it out on your server?

You should see the whole application code. There isn't a docroot directory in this application but a web directory which is what should be accessible to the public. Also there isn't a index.php file but a app.php file (as standard for a Symfony app). Has your server been configured to point to the web directory?

**Comment by DaisyMaeHarris** [comment]
Thank you, I cloned the project from https://github.com/teamdeeson/warden

It is interesting to know there is no docroot folder, thank you.

I also see a directory called 'web' which contains:
app_dev.php, apple-touch-icon.png, app.php, bundles, config.php, favicon.ico, robots.txt

Does that sound like the correct directory to point my URL to so I may browse to the dashboard?

**Comment by mikeddeeson** [comment]
Yes this is the directory that you should be pointing your domain to within the configuration of your server.

Do you just have a default set up currently on your server then with a default home page within your docroot directory?

**Comment by DaisyMaeHarris** [comment]
That must be what I've done, thank you. Docksal must have created the docroot folder and put index.php inside it. I had incorrectly assumed that was part of the Warden application. Thank you for explaining and your fast replies. I will configure the server to look at that folder. At the moment if I browse to http://warden.mydomain.com/web or http://warden.mydomain.com/web/app.php I get a 404 error but I'm sure I can sort that with server configuration. I shall look now, thank you.

**Comment by DaisyMaeHarris** [comment]
Thanks for your help, I'm continuing to troubleshoot - my nginx server is perhaps struggling with this part of warden/web/app.php Perhaps I have not pointed it correctly. I will post information here if I manage to sort it out.

`// When using the HttpCache, you need to call the method in your front controller instead of relying on the configuration parameter
//Request::enableHttpMethodParameterOverride();
Request::setTrustedProxies(['127.0.0.1'], Request::HEADER_X_FORWARDED_ALL);
$request = Request::createFromGlobals();
$response = $kernel->handle($request);
$response->send();
$kernel->terminate($request, $response);`

**Comment by DaisyMaeHarris** [comment]
Just adding my solution in case it is helpful to anybody else:
1) I installed Apache instead of nginx.
2) I gave www-data:www-data ownership to the var/log and var/cache folders in the warden folder.

This seems to have worked.

**Comment by mikeddeeson** [comment]
Glad that you managed to get your server configured correctly :). 

It does depend upon how your web server (apache / nginx) is configured as to how it will run, but this is all down the server configuration in order to get a Symfony application running.

We have currently got it running under Nginx for local development as well as for our own sites. and we have used Apache in the past for this as well.
