### ISSUE TITLE
Mongo DB php driver requirements

### ISSUE THREAD

**Issue by drclaw** [teamdeeson/warden#60]
The currently recommended php driver for mongo db appears to be incompatible with warden. The recommended driver on [docs.mongodb.org](https://docs.mongodb.org/ecosystem/drivers/php/) is [mongodb](https://pecl.php.net/package/mongodb), whereas it appears warden requires the older "legacy" [mongo](https://pecl.php.net/package/mongo) driver. At least, if we're basing it entirely on the name "mongodb" vs just "mongo" - which from what I can tell is how you tell the difference.

Furthermore, it looks like the newest version of mongo db is incompatible with the legacy php driver according to the [docs](https://docs.mongodb.org/ecosystem/drivers/php/#mongodb-compatibility).

So I guess my question is, is there a specific mongodb version and php driver version requirement?

**Comment by mikeddeeson** [comment]
Hi @drclaw,

The installation of Mongodb and PHP is a requirement in order to be able to use Warden, but we haven't detailed anywhere (as far as I am aware) any specific versions of this?

Are you referring to the mongo drivers listed in the composer file?

Thanks
Mike

**Comment by drclaw** [comment]
Hi,

Yeah, I guess we're talking specifically about `doctrine/mongodb` which relies on the legacy php driver `mongo`. I did a bit of digging and there's actually an issue that discusses upgrading `doctrine/mongodb` to use the newer php driver: https://github.com/doctrine/mongodb/issues/239. (tl;dr 'We haven't yet decided exactly on how we'll handle the migration to PHP 7 and ext-mongodb other than "it will happen".')

So, I wonder if maybe I just need to kick my version of mongodb back to one that's compatible with the older driver? What version of mongodb are you running?

Thanks!
drclaw

**Comment by mikeddeeson** [comment]
Hi @drclaw,

Sorry for the late reply to this ... we have been having a look more recently at the mongo drivers as it seems that there has been some changes with what is recommended and what Doctrine support etc.

We have been running on the older version of Mongo, but we have been trying with the new version more recently and have come across these same problems.

We are looking at putting some more detailed instructions together which we will be including to help users with installing the right driver etc., but the following is what we currently have:

-----------

## Swapping the legacy driver for the new driver

The MongoDB team provide a legacy driver named “mongo” and they provide the new recommended driver “mongodb”. Both can be installed via PHP’s PECL cli. The new driver has a very different API to the legacy driver so the MongoDB provide a userland PHP library which wrappers the new driver to provide an API similar to the legacy driver’s API.

The following page on the MongoDB docs site explains more about the different types of driver, the user land PHP library and compatibility with different MongoDB server versions and PHP language versions.

https://docs.mongodb.com/ecosystem/drivers/php/

Currently the Doctrine MongoDB ODM bundle depends upon the API provided by the legacy MongoDB driver. As the userland PHP library that wrappers the new MongoDB driver is only similar but not identical to the legacy driver’s API, the Doctrine MongoDB ODM bundle will throw an exception similar to the following because the Mongo class is missing:

`PHP Fatal error:  Class 'MongoClient' not found in /export/warden/vendor/doctrine/mongodb/lib/Doctrine/MongoDB/Connection.php on line 96`

To provide a MongoDB driver API that is identical to the legacy driver’s API so that the Doctrine MongoDB ODM bundle can function the Doctrine team have produced an adapter library which wrappers the MongoDB PHPLIB (the userland PHP library which wrappers the new driver).

## Installing the new libraries

All the libraries required to make the Doctrine MongoDB ODM package function with the new MongoDB PHP driver can be installed via composer. Note that you will require version 5.5 of PHP or above in order to use these libraries.

Composer will require the following lines adding to composer.json:

`"mongodb/mongodb": "^1.0",
"alcaeus/mongo-php-adapter": "^1.0"`

The mongodb/mongodb package will install the MongoDB PHPLIB library and it requires the metapackage ext-mongodb, which performs a platform check to see if the new MongoDB driver has been loaded by PHP.

The alcaeus/mongo-php-adapter package will install the Doctrine team’s adapter library.

Those lines should be sufficient to have Composer install the necessary dependencies. However, due to a bug with Composer, upon trying to composer install/update you will receive a warning that a dependency on ext-mongo cannot be satisfied.

ext-mongo is a Composer metapackage. Requiring ext-mongo forces Composer into performing a platform check to see if the legacy MongoDB driver has been loaded by PHP. The legacy MongoDB driver should not be loaded by PHP as its definition of the Mongo class (and other legacy driver classes) will conflict with those provided by the Doctrine team’s adapter library.

The Doctrine team’s adapter library does have the correct Composer metadata present to say that it will be providing a suitable implementation of ext-mongo, but this does not work correctly in Composer at the moment due to this bug: https://github.com/composer/composer/issues/5030

The solution at currently is to add the follow lines (below the require block is sufficient) to your Composer.json:

`"provide": {
        "ext-mongo": "1.6.13"
    },`

Those lines tell Composer that the platform provides the package ext-mongo at version 1.6.13 and prevents Composer from performing the platform check. If you composer install/update now Composer should run to completion without error.

--------

Does this help with your installation?

Thanks
Mike

**Comment by asrob** [comment]
Hi Mike,

Yes, it was helpful. It seems to work with branch "mongodb-32". I got an error message but AFAIK there is an issue about this:

> Script Deeson\WardenBundle\Composer\ScriptHandler::setupWarden handling the post-update-cmd event terminated with an exception  [ErrorException]  file_put_contents(/Users/asrob/Sites/warden/app/../src/Deeson/WardenBundle/Resources/public/css/warden-custom.css): failed to open stream: No such file or directory

**Comment by mikeddeeson** [comment]
Hi Peter,

Thanks for confirming this - we are have been running on this branch for a while testing this fix and it seems to be running well.

Yes this error was fixed recently, which I had committed into the master branch. I have merged this now to the "mongodb-32" branch so if you update this version you should have this fix.

As you are running the "mongodb-32" branch, we would appreciate any feedback/ issues that you have with the Mongodb driver. We have been running this version for a while now without any issues and it seems stable enough to be merged to the master branch ready for a new release.

Thanks
Mike

**Comment by asrob** [comment]
Hi Mike,

I think this is stable enough to be merged to the master branc, therefore #61 is ready as well. What do you think?

**Comment by mikeddeeson** [comment]
Thanks Peter - always good to have other people using it :). We have been using it for a while without any issues so I was thinking that it was ready for release also.

**Comment by asrob** [comment]
Yes, I would like to introduce Warden to my colleagues at the company. I hope I will be able to help you more . :)

**Comment by mikeddeeson** [comment]
That would be great - always nice to get information about how other people are using the system and enhancements that would make it a much better product :).

**Comment by mikeddeeson** [comment]
The `mongodb-32` branch has been merged to the `master` branch which updates this driver version now
