### ISSUE TITLE
Webform module is showing as needing a security update when it does not

### ISSUE THREAD

**Issue by johnennewdeeson** [teamdeeson/warden#76]
![image](https://cloud.githubusercontent.com/assets/1913439/20560725/c457627a-b172-11e6-9887-7ebfee2d6286.png)

7.x-3.25 was a security release and has been deployed to the site
7.x-3.26-rc1 is not a security release but Warden is saying this site needs a security update by making the line red.

Maybe a problem with the newer release being a release candidate?

**Comment by mikeddeeson** [comment]
Hi @johnennewdeeson,

I have been having a look at this and it looks like it is not detecting it correctly when you select to refresh the site. However once the cron runs to update the site with the Drupal modules, then the correct status is set.

I will have a look to see why this is not showing correctly on the site refresh.

Thanks
Mike

**Comment by mikeddeeson** [comment]
Hi @johnennewdeeson,

Looking at this further, the reason that the module is still showing as needing a security update following a site refresh is because Warden has only updated the version of that module for the site at this point. It currently doesn't compare this against Drupal's API to know if it is greater than or equal to the security update release version.

Warden currently only stores whether a module is requiring a security update against a site. It therefore doesn't know when the site is refreshed if the version that the site has is no longer out of date or not.

When cron next runs, this updates the module details and then sets whether the module needs a security update or not based upon the version of the module for the site.

An enhancement could be to change this so that on a site refresh the module version are checked against module document itself to check the version to determine if it is still an out of date module version.

Thanks
Mike
